version: '3'
services:
  spark-submit:
    image: metorikku/metorikku:standalone
    environment:
    - SUBMIT_COMMAND=spark-submit --conf spark.sql.warehouse.dir=/warehouse  --class com.yotpo.metorikku.Metorikku metorikku.jar -c examples/hive/movies.yaml
    - HIVE_METASTORE_URI=hive:9083
    entrypoint:
      - /scripts/entrypoint-submit.sh
    volumes:
      - ./output/:/examples/output/
    depends_on:
      - spark-master
      - spark-worker
      - hive
  hive-tester:
    image: metorikku/metorikku:standalone
    environment:
      - SUBMIT_COMMAND=spark-submit --conf spark.sql.warehouse.dir=/warehouse  --class com.yotpo.metorikku.MetorikkuTester metorikku.jar --test-settings examples/hive/movies_test.yaml
      - HIVE_METASTORE_URI=hive:9083
    volumes:
      - ./output/:/examples/output/
      - ./warehouse:/warehouse
    entrypoint:
      - /scripts/entrypoint-submit.sh
    depends_on:
      - spark-master
      - spark-worker
  spark-master:
    image: metorikku/metorikku:standalone
    entrypoint:
      - /scripts/entrypoint-master.sh
    logging:
      driver: none
  spark-worker:
    image: metorikku/metorikku:standalone
    entrypoint:
      - /scripts/entrypoint-worker.sh
    volumes:
      - ./output/:/examples/output/
      - ./warehouse:/warehouse
    logging:
      driver: none
  hive:
    image: metorikku/hive
    environment:
      - CONNECTION_URL=jdbc:mysql://hive-db:3306/hive?useSSL=false
      - CONNECTION_USER_NAME=root
      - CONNECTION_PASSWORD=pass
      - WAREHOUSE_DIR=file:///warehouse
      - WAIT_HOSTS=hive-db:3306
    depends_on:
      - hive-db
  hive-db:
    image: mysql:5.7.25
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=hive
