addSbtPlugin("com.github.sbt"   % "sbt-release"           % "1.1.0")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"  % "0.10.0-RC1")
addSbtPlugin("org.scalastyle"  %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"          % "3.9.15")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"          % "2.4.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.0")
