# docker-compose up --exit-code-from elasticsearch_tester
version: '3'
services:
  spark-submit:
    image: metorikku/metorikku
    environment:
      - SUBMIT_COMMAND=spark-submit --packages commons-httpclient:commons-httpclient:3.0.1 --jars https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-hadoop/6.8.10/elasticsearch-hadoop-6.8.10.jar --class com.yotpo.metorikku.Metorikku metorikku.jar -c examples/elasticsearch/movies.yaml
    entrypoint:
      - /scripts/entrypoint-submit.sh
    depends_on:
      - spark-master
      - spark-worker
  spark-master:
    image: metorikku/metorikku
    entrypoint:
      - /scripts/entrypoint-master.sh
    logging:
      driver: none
  spark-worker:
    image: metorikku/metorikku
    entrypoint:
      - /scripts/entrypoint-worker.sh
    logging:
      driver: none
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - network.publish_host=elasticsearch
      - http.publish_host=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
  elasticsearch-tester:
    image: "circleci/buildpack-deps:stretch-curl"
    volumes:
      - ./scripts:/scripts
      - ./mocks:/mocks
    command: /scripts/elasticsearch_test.sh
    environment:
      - MOCK_OUTPUT=/mocks/movies.json
      - INDEX_NAME=movies
      - SORTBY=movieid
      - DEBUG=true
  elasticsearch-init:
    image: "circleci/buildpack-deps:stretch-curl"
    volumes:
      - ./scripts:/scripts
    command: /scripts/elasticsearch_init.sh
    environment:
      - INDEX_NAME=movies
