# docker-compose up --exit-code-from influxdb_tester
version: '3'
services:
  spark-submit:
    image: metorikku/metorikku:standalone
    environment:
      - SUBMIT_COMMAND=spark-submit --class com.yotpo.metorikku.Metorikku metorikku.jar -c examples/influxdb/movies.yaml
    entrypoint:
      - /scripts/entrypoint-submit.sh
    depends_on:
      - spark-worker
      - spark-master
  spark-master:
    image: metorikku/metorikku:standalone
    entrypoint:
      - /scripts/entrypoint-master.sh
    logging:
      driver: none
  spark-worker:
    image: metorikku/metorikku:standalone
    entrypoint:
      - /scripts/entrypoint-worker.sh
    logging:
      driver: none
  influxdb:
    image: influxdb:1.7.8
    environment:
      - INFLUXDB_ADMIN_USER=user
      - INFLUXDB_ADMIN_PASSWORD=pass
      - INFLUXDB_DB=test
      - INFLUXDB_HTTP_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
  influxdb-tester:
    image: buildpack-deps:stretch-curl
    volumes:
      - ./scripts:/scripts
      - ./mocks:/mocks
    command: /scripts/influx_test.sh
    environment:
      - MOCK_OUTPUT=/mocks/ratings.json
      - QUERY=SELECT time, genre, metric, number_of_ratings FROM moviesAppInflux WHERE genre != ''
