name: "Build DevContainer image"

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - main
      - master
    paths:
      - .devcontainer/**
      - pyproject.toml
      - build.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v2
        with:
          use: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create envfile
        run: |
          echo 'GITHUB_USER=${{ github.repository_owner }}' >> .env
          echo 'GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}' >> .env
      - name: Prune
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: ${{ github.event.repository.name }}
          keep-last: 6
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/${{ github.repository }}:devcontainer
          push: true
          file: .devcontainer/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
